import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/Shared/Navbar";



export const metadata = {
  title: "TalkHub",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html
      lang="en"
      
    >
      <body className="min-h-full flex flex-col">

        <header>
          <Navbar />
        </header>

        <main>
          {children}
        </main>
      </body>
    </html>
  );
}
